who03: my_wholib.c my_who03.c
	gcc my_wholib.c my_who03.c -o who03

who02: my_who02.c
	gcc my_who02.c -o who02

who01: my_who01.c
	gcc my_who01.c -o who01

copy: copy01.c
	gcc copy01.c -o copy

logout: logout.c
	gcc logout.c -o my_logout
