exec1: exec1.c
	gcc exec1.c -o exec1

psh1: psh1.c
	gcc psh1.c -o psh1

psh2: psh2.c
	gcc psg2.c -o psh2

fork1: forkdemo1.c
	gcc forkdemo1.c -o fork1

fork2: forkdemo2.c
	gcc forkdemo2.c -o fork2

wait1: waitdemo1.c
	gcc waitdemo1.c -o wait1

wait2: waitdemo2.c
	gcc waitdemo2.c -o wait2

clean: 
	rm -f exec1 psh1 psh2 fork1 fork2 wait1 wait2
