get_response01: get_response01.c 
	gcc get_response01.c -o get_response01
get_response02: get_response02.c
	gcc get_response02.c -o get_response02
get_response03: get_response03.c
	gcc get_response03.c -o get_response03
sigdemo: sigdemo01.c
	gcc sigdemo01.c -o sigdemo

clean: 
	rm -f get_response01 get_response02 get_response03 sigdemo
